export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL';

export const FETCH_WHITEMS_START = 'FETCH_WHITEMS_START';
export const FETCH_WHITEMS_SUCCESS = 'FETCH_WHITEMS_SUCCESS';
export const FETCH_WHITEMS_FAIL = 'FETCH_WHITEMS_FAIL';

export const ADD_CATEGORY_TO_FILTER = 'ADD_CATEGORY_TO_FILTER';
export const REMOVE_CATEGORY_FROM_FILTER = 'REMOVE_CATEGORY_FROM_FILTER';


export const FETCH_MYITEMS_START = 'FETCH_MYITEMS_START';
export const FETCH_MYITEMS_SUCCESS = 'FETCH_MYITEMS_SUCCESS';
export const FETCH_MYITEMS_FAIL = 'FETCH_MYITEMS_FAIL';


export const SEND_SWAP_START = 'SEND_SWAP_START';
export const SEND_SWAP_SUCCESS = 'SEND_SWAP_SUCCESS';
export const SEND_SWAP_FAIL = 'SEND_SWAP_FAIL';
export const SEND_INIT = 'SEND_INIT';

export const DELETE_SWAP_SUCCESS = 'DELETE_SWAP_SUCCESS';
export const DELETE_SWAP_FAIL = 'DELETE_SWAP_FAIL';

export const FETCH_MYREQUESTS_SUCCESS = 'FETCH_MYREQUESTS_SUCCESS';
export const FETCH_MYREQUESTS_FAIL = 'FETCH_MYREQUESTS_FAIL';

export const TAKE_WHITEM_SUCCESS = 'TAKE_WHITEM_SUCCESS';
export const TAKE_WHITEM_FAIL = 'TAKE_WHITEM_FAIL';

export const RETURN_WHITEM_SUCCESS = 'RETURN_WHITEM_SUCCESS';
export const RETURN_WHITEM_FAIL = 'RETURN_WHITEM_FAIL';


export const FETCH_ITEMREQUESTS_SUCCESS = 'FETCH_ITEMREQUESTS_SUCCESS';
export const FETCH_ITEMREQUESTS_FAIL = 'FETCH_ITEMREQUESTS_FAIL';


export const PERFORM_ITEMREQUESTS_SUCCESS = 'PERFORM_ITEMREQUESTS_SUCCESS';
export const PERFORM_ITEMREQUESTS_FAIL = 'PERFORM_ITEMREQUESTS_FAIL';

export const CANCEL_ITEMREQUESTS_SUCCESS = 'CANCEL_ITEMREQUESTS_SUCCESS';
export const CANCEL_ITEMREQUESTS_FAIL = 'CANCEL_ITEMREQUESTS_FAIL';


export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';


export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';
